name: Deploy React App
on: push
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: macOS-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}  
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build:
    needs: [lint, test]
    strategy:
      matrix:
        node-version: [14, 16]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Buildapplication
        run: npm run build
      - name: Deploy
        run: echo Deploying...
      