name: Deploy React App
on: push
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: macOS-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}  
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build:
    runs-on: macOS-latest
    needs: [lint, test]
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Buildapplication
        run: npm run build
      - name: Deploy
        run: echo Deploying...
      